### ISSUE TITLE
Buttons overflow in FireFox browser

### ISSUE THREAD

**Issue by Bisuz** [Prasanta-Hembram/Multiscript-UI-Calculator#5]
* Button overflow can be solve in FireFox by making changes in CSS.
![Screenshot (22)](https://user-images.githubusercontent.com/90062706/196872209-fa502897-7e54-4987-b812-3686932d96c0.png)

**Comment by Prasanta-Hembram** [comment]
Hey @Bisuz , thanks for contributing here. The main **eng** folder template is used in all the other locales, so whatever you make change also consider changing to all the other locale too if possible :-)..Tell me if something is not clear.

**Comment by Prasanta-Hembram** [comment]
#7

**Comment by Prasanta-Hembram** [comment]
Thanks for your contribution.
