### ISSUE TITLE
Embedding one css file for multiple html files

### ISSUE THREAD

**Issue by Prasanta-Hembram** [Prasanta-Hembram/Multiscript-UI-Calculator#9]
* Every locale folder (eg. hi, sat, or etc.) have the same css file in their respective folders.
* The task is to host the css in one place for multiple html files.
* Can you do it, ask questions if still clear.

**Comment by pixobia** [comment]
please assign me this issue,i will work on it..

**Comment by Prasanta-Hembram** [comment]
@pixobia best of luck..👍👍

**Comment by pixobia** [comment]
#9 resolved pls merge my pull request..
